# Server
server.port=9999

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/kitchensink
spring.data.mongodb.auto-index-creation=true

## Thymeleaf
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

# Validation
spring.mvc.throw-exception-if-no-handler-found=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Disable JSF
spring.jmx.enabled=false
spring.main.web-application-type=servlet